apiVersion: v1
kind: Service

metadata:
  name: graf-svc
  labels: 
    env: monitoring
  
spec:
  ports:
    - port: 3000
      nodePort: 31100
  selector:
    env: monitoring
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana
  labels:
    env: monitoring

spec:
  selector:
    matchLabels:
      env: monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: monitoring

    spec:
      containers:
      - image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: graf-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: graf-storage
        persistentVolumeClaim:
          claimName: graf-pvc